name: pm01-ox
channels:
  - conda-forge
dependencies:
  - python=3.8.10
  # libpython and m2w64-toolchain install a c++ compiler for pymc3-theano.
  # However, these packages are only available on Windows.
  # - libpython=2.1
  # - m2w64-toolchain=5.3.0
  - notebook=6.1.4
  - mkl-service=2.3.0
  - nbgrader=0.6.1
  # nbgrader 0.6.1 is not compatible with sqlalchemy 1.4 so we force 1.3 here:
  - sqlalchemy=1.3
  # nbgrader 0.6.1 is not compatible with jinja2 3.x, so we force 2.11 here:
  - jinja2=2.11
  # nbgrader 0.6.1 is not compatible nbconvert 6.x, so we force 5.6 here:
  - nbconvert=5.6
  - jupyterhub=1.1.0
  - numpy=1.19.1
  - matplotlib=3.3.1
  - pandas=1.1.3
  - scipy=1.5.0
  - seaborn=0.11
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.2
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - python-graphviz=0.14.2
  - nose=1.3.7
  - pip=20.2.3
  - biopython=1.78
  - requests=2.24.0
  - pyyaml=5.3.1
  - scikit-learn-extra=0.1.0b2
  - ipywidgets=7.5.1
  - sympy=1.6.2
  - pytables=3.6.1
  - patsy=0.5.1
  - pip:
      - adskalman==0.3.11
      - arviz==0.11.2
      - pymc3==3.11.2
      - dabest==0.3.1
