name: test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15, macos-11]

    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: false

      - name: Create and test newly created conda environment
        shell: bash -l {0}
        run: |
          conda env create --name TEST --file environment.yml
          source activate TEST
          if [ "$RUNNER_OS" == "Windows" ]; then
              # Ideally these packages would be in environment.yml but they
              # are only needed (and available) on Windows.
              conda install --yes libpython=2.1 m2w64-toolchain=5.3.0
          fi
          python testing/test_pymc3.py
